version: '3.8'

services:
  user-service:
    build: .
    command: uvicorn app:app --reload --port 8000
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
